### ISSUE TITLE
Path in readme incorrect

### ISSUE THREAD

**Issue by numtel** [niaquinto/docker-gradle#11]
The readme lists the following command to run a gradle task:
```
docker run --rm -v /path/to/your/project:/usr/src/app:rw niaquinto/gradle clean war
```

But the directory in the container should instead be `/usr/bin/app`.

**Comment by niaquinto** [comment]
@fiunchinho was kind enough to submit #10 fixing this. And, I've since went though and tagged the new versions he added (2.12, 2.13). These are now `docker pull`-able. And, the `latest` container points to Gradle version 2.13.

Thanks!
