### ISSUE TITLE
Change in WORKDIR breaks the backward compatibility

### ISSUE THREAD

**Issue by praveen12bnitt** [niaquinto/docker-gradle#3]
Looks like after upgrading to 2.6, you also changed the WORKDIR from /app to /usr/bin/app. This breaks the backward compatibility of the image. I spent a whole day trying to figure out why my existing docker compose scripts suddenly failed.

Either restore the WORKDIR to /app or document the change in dockerhub and github.

**Comment by niaquinto** [comment]
I've updated the docs to reflect the new WORKDIR (9039507239cd2af62bb6f887c9634c621a38d466). 

This is a persistent problem with Docker. You should be very careful about the images you depend on. I'm just some random guy, after all. More specifically, it is usually not a good idea to use "latest", when there is a possibility that the image could introduce breaking changes.

**Comment by niaquinto** [comment]
To clarify, I should have added documentation before changing. And, I don't mean to be accusatory. Just a best-practices suggestion!

**Comment by niaquinto** [comment]
To clarify, I should have added documentation before changing. And, I don't mean to be accusatory. Just a best-practices suggestion!

**Comment by praveen12bnitt** [comment]
Got it, thanks..

**Comment by niaquinto** [comment]
To update, and sorry for the change again. I've updated the image again to use `/usr/src/app`. My original intention for the change was to be in-line with the onbuild versions of standard programming language containers (ex. [python:3-onbuild](https://github.com/docker-library/python/blob/7663560df7547e69d13b1b548675502f4e0917d1/3.4/onbuild/Dockerfile)).
