### ISSUE TITLE
Update to Gradle 2.7

### ISSUE THREAD

**Issue by Sloy** [niaquinto/docker-gradle#6]
Gradle 2.7 is now available. I would send you a pull request myself, but I'm missing the md5 hash. 

If you could tell me where did you find the current hash, or if you generated it manually, I will gladly send a pull request with the newer version.

Thanks

**Comment by stepan-romankov** [comment]
+1

**Comment by niaquinto** [comment]
Hey! Thanks for prompting me on this. I've updated the image to 2.7. So, now the `latest` tag on docker hub is 2.7, and there is a seperate `2.7` tag if you'd like to track that version specifically. Moreover, there is now a `2.6` tag as well, b/c docker hub fixed the issue, where that tab of the SPA was 503 erroring.

**Comment by Sloy** [comment]
Thank you :)

**Comment by niaquinto** [comment]
Also, I realize I didn't answer your question about the md5 hash. I compute it myself by downloading the archive and running `md5 {filename}` on OSX or `md5sum {filename}` on linux.

**Comment by Sloy** [comment]
Ah ok @niaquinto, I thought you might be copying it from the website or something. Thanks :)
